# run dockefile + postgres
services:
  webserver:
    build: 
      context: .
      dockerfile: webserver.Dockerfile
    container_name: webserver
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data/webserver/log.txt:/data/webserver/log.txt
    depends_on:
      - db
    networks:
      - webnet

  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: postgres
    restart: always
    #user: "1000:1000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: webserver_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - webnet


networks:
  webnet:
    driver: bridge
    name: webnet