services:
  webserver:
    build: .
    container_name: webserver
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data:/data
    networks:
      - webnet


networks:
  webnet:
    driver: bridge
    name: webnet